apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: qafrontend-mapping
  namespace: qa
  labels:
    hostname: qa.flyme247.com
  annotations: {}
spec:
  bypass_auth: true
  cors:
    methods:
    - PUT, POST, GET, DELETE, PATCH, OPTIONS
    origins:
    - "*"
    v2CommaSeparatedOrigins: true
  hostname: qa.flyme247.com
  prefix: /
  rewrite: /
  service: frontend:80
  timeout_ms: 60000
