apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: frontend-mapping-1651931063960
  namespace: qa
  labels: null
  annotations: {}
spec:
  ambassador_id:
  - default
  connect_timeout_ms: 3000
  hostname: qa.flyme247.com
  prefix: /
  retry_policy:
    num_retries: 1
    per_try_timeout: 0.150s
    retry_on: 5xx
  service: frontend.qa:80
  timeout_ms: 3000
