apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: qafrontend-mapping
  namespace: qa
  labels:
    hostname: qa.flyme247.com
spec:
  hostname: "https://qa.flyme247.com"
  prefix: /
  rewrite: /
  service: frontend:80
  bypass_auth: true
  timeout_ms: 60000
  cors:
    origins: "*"
    methods: PUT, POST, GET, DELETE, PATCH, OPTIONS
